#!/bin/bash

# Check if the script is being run with root privileges
if [ "$EUID" -ne 0 ]; then
        echo "Please run this script as root or with sudo."
        exit
fi

apt update
xargs apt install -y < package.list
